### ISSUE TITLE
python client same to android app,这样也可以通过脚本来下单了

### ISSUE THREAD

**Issue by cjw123ztt** [cjw123ztt/stocktupoui#55]
https://github.com/pika/pika
https://pika.readthedocs.io/en/stable/
https://www.jianshu.com/p/7147c0070224
pip install pika
Python 2.7 and 3.4+ are supported.
![image](https://user-images.githubusercontent.com/32285324/91929387-d8c0e000-ed10-11ea-8c5f-80e8d4b49953.png)

**Comment by cjw123ztt** [comment]
uri=amqp://covprbbm:9exUT3KY19XpOfngiwkFVj99KOmM1xV5@fish.rmq.cloudamqp.com/covprbbm
clientid=

**Comment by cjw123ztt** [comment]
exchange        = "amq.fanout"
routing_key     ="NA"
MAIL_TAG        = "mailTag"
MAIL_SUBJECT    = "mailSubject"
MAIL_SENDER     = "mailSender"
MAIL_RECEIVER   = "mailReceiver"
def on_message_callback(ch,method,properties,body):
    print("on_message_callback")
    print(properties)
    print(body)
    logging.info(body)

if __name__ == '__main__':
    connection = pika.BlockingConnection(pika.URLParameters(uri))
    #
    channel = connection.channel()
    channel.queue_declare(clientid,False,False,True)
    channel.queue_bind(clientid,exchange,routing_key)
    #basic_publish(exchange, routing_key, body, properties=None, mandatory=False)
    #hdrs = {u'مفتاح': u' قيمة', u'键': u'值', u'キー': u'値'}
    hdrs={}
    hdrs[MAIL_TAG]     = "query lzBankuaiFuture"
    hdrs[MAIL_SUBJECT] = "query lzBankuaiFuture"
    hdrs[MAIL_SENDER]  = clientid
    properties = pika.BasicProperties(
        app_id='example-publisher',
        content_type='application/json',
        headers=hdrs)
    channel.basic_publish(exchange,routing_key,"python pc client hello",properties)
    channel.basic_consume(clientid,on_message_callback)
    channel.start_consuming()
    channel.close()
    connection.close()

**Comment by cjw123ztt** [comment]
https://www.cnpython.com/pypi/handout
markdown转换成html,用浏览器xian

**Comment by cjw123ztt** [comment]
Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\tornado\websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

**Comment by cjw123ztt** [comment]
Jupyter Notebook environment anaconda3 error
https://www.jianshu.com/p/7d8ce818a923

**Comment by cjw123ztt** [comment]
Ensuring well-behaved connection with heartbeat and blocked-connection timeouts
https://github.com/pika/pika/blob/master/docs/examples/heartbeat_and_blocked_timeouts.rst

**Comment by cjw123ztt** [comment]
1.(base) C:\Users\dfc>jupyter notebook --generate-config
Writing default config to: C:\Users\dfc\.jupyter\jupyter_notebook_config.py(改了之后不工作的)
https://www.cnblogs.com/dj1232090/p/10648678.html
2.将目标最后的%USERPROFILE%替换成目标路径才可以

**Comment by cjw123ztt** [comment]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/
